// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: DFSgDk7xEF4uDtL4KTuii
// Component: 3Hl0KWOcfg

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import VillaListing from "../../VillaListing"; // plasmic-import: vwSSb6HVzl/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_visitors_css from "../visitors/plasmic_visitors.module.css"; // plasmic-import: w4yYo48qoeavp6MLu5USrX/projectcss
import projectcss from "./plasmic_blank_website.module.css"; // plasmic-import: DFSgDk7xEF4uDtL4KTuii/projectcss
import sty from "./PlasmicVillaListing2.module.css"; // plasmic-import: 3Hl0KWOcfg/css

export type PlasmicVillaListing2__VariantMembers = {};
export type PlasmicVillaListing2__VariantsArgs = {};
type VariantPropType = keyof PlasmicVillaListing2__VariantsArgs;
export const PlasmicVillaListing2__VariantProps = new Array<VariantPropType>();

export type PlasmicVillaListing2__ArgsType = {
  villaDetails?: any;
};
type ArgPropType = keyof PlasmicVillaListing2__ArgsType;
export const PlasmicVillaListing2__ArgProps = new Array<ArgPropType>(
  "villaDetails"
);

export type PlasmicVillaListing2__OverridesType = {
  root?: p.Flex<typeof VillaListing>;
};

export interface DefaultVillaListing2Props {
  villaDetails?: any;
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicVillaListing2__RenderFunc(props: {
  variants: PlasmicVillaListing2__VariantsArgs;
  args: PlasmicVillaListing2__ArgsType;
  overrides: PlasmicVillaListing2__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {
          villaDetails: {
            html_folder: "aquila-villa",
            villa_name: "Aquila Villa",
            main_image: "Aquila-Villa(1).jpg",
            location: "Crete, Chania, Drapanos village",
            bedrooms: 4,
            sleeps: 10,
            bathrooms: 5,
            pool_type: "private",
            car: "recommended",
            description:
              "A sea side villa with private pool, indescribable sea view, modern decoration and equipped with all the necessary amenities to offer you a luxury stay.",
            price_min: 2000
          }
        },
        props.args
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  return (
    <VillaListing
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames("__wab_instance", sty.root)}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: typeof VillaListing;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicVillaListing2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicVillaListing2__VariantsArgs;
    args?: PlasmicVillaListing2__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicVillaListing2__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicVillaListing2__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicVillaListing2__ArgProps,
          internalVariantPropNames: PlasmicVillaListing2__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicVillaListing2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicVillaListing2";
  } else {
    func.displayName = `PlasmicVillaListing2.${nodeName}`;
  }
  return func;
}

export const PlasmicVillaListing2 = Object.assign(
  // Top-level PlasmicVillaListing2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicVillaListing2
    internalVariantProps: PlasmicVillaListing2__VariantProps,
    internalArgProps: PlasmicVillaListing2__ArgProps
  }
);

export default PlasmicVillaListing2;
/* prettier-ignore-end */
