// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: DFSgDk7xEF4uDtL4KTuii
// Component: TIB8lH87Th

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import HomeSlide2 from "../../HomeSlide2"; // plasmic-import: wtJWL5MKRdX/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_visitors_css from "../visitors/plasmic_visitors.module.css"; // plasmic-import: w4yYo48qoeavp6MLu5USrX/projectcss
import projectcss from "./plasmic_blank_website.module.css"; // plasmic-import: DFSgDk7xEF4uDtL4KTuii/projectcss
import sty from "./PlasmicHomeSlide.module.css"; // plasmic-import: TIB8lH87Th/css

export type PlasmicHomeSlide__VariantMembers = {};
export type PlasmicHomeSlide__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomeSlide__VariantsArgs;
export const PlasmicHomeSlide__VariantProps = new Array<VariantPropType>();

export type PlasmicHomeSlide__ArgsType = {};
type ArgPropType = keyof PlasmicHomeSlide__ArgsType;
export const PlasmicHomeSlide__ArgProps = new Array<ArgPropType>();

export type PlasmicHomeSlide__OverridesType = {
  root?: p.Flex<"div">;
  homeSlide2?: p.Flex<typeof HomeSlide2>;
};

export interface DefaultHomeSlideProps {
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomeSlide__RenderFunc(props: {
  variants: PlasmicHomeSlide__VariantsArgs;
  args: PlasmicHomeSlide__ArgsType;
  overrides: PlasmicHomeSlide__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_visitors_css.plasmic_tokens,
        sty.root
      )}
    >
      <HomeSlide2
        data-plasmic-name={"homeSlide2"}
        data-plasmic-override={overrides.homeSlide2}
        className={classNames("__wab_instance", sty.homeSlide2)}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "homeSlide2"],
  homeSlide2: ["homeSlide2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  homeSlide2: typeof HomeSlide2;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomeSlide__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomeSlide__VariantsArgs;
    args?: PlasmicHomeSlide__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomeSlide__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicHomeSlide__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicHomeSlide__ArgProps,
          internalVariantPropNames: PlasmicHomeSlide__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomeSlide__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomeSlide";
  } else {
    func.displayName = `PlasmicHomeSlide.${nodeName}`;
  }
  return func;
}

export const PlasmicHomeSlide = Object.assign(
  // Top-level PlasmicHomeSlide renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    homeSlide2: makeNodeComponent("homeSlide2"),

    // Metadata about props expected for PlasmicHomeSlide
    internalVariantProps: PlasmicHomeSlide__VariantProps,
    internalArgProps: PlasmicHomeSlide__ArgProps
  }
);

export default PlasmicHomeSlide;
/* prettier-ignore-end */
