// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: DFSgDk7xEF4uDtL4KTuii
// Component: ZBhwsxC3jh

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import RecommendedVillas2 from "../../RecommendedVillas2"; // plasmic-import: HBIlN8IHFlq/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_visitors_css from "../visitors/plasmic_visitors.module.css"; // plasmic-import: w4yYo48qoeavp6MLu5USrX/projectcss
import projectcss from "./plasmic_blank_website.module.css"; // plasmic-import: DFSgDk7xEF4uDtL4KTuii/projectcss
import sty from "./PlasmicRecommendedVillas.module.css"; // plasmic-import: ZBhwsxC3jh/css

export type PlasmicRecommendedVillas__VariantMembers = {};
export type PlasmicRecommendedVillas__VariantsArgs = {};
type VariantPropType = keyof PlasmicRecommendedVillas__VariantsArgs;
export const PlasmicRecommendedVillas__VariantProps =
  new Array<VariantPropType>();

export type PlasmicRecommendedVillas__ArgsType = {};
type ArgPropType = keyof PlasmicRecommendedVillas__ArgsType;
export const PlasmicRecommendedVillas__ArgProps = new Array<ArgPropType>();

export type PlasmicRecommendedVillas__OverridesType = {
  root?: p.Flex<"div">;
  recommendedVillas2?: p.Flex<typeof RecommendedVillas2>;
};

export interface DefaultRecommendedVillasProps {
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicRecommendedVillas__RenderFunc(props: {
  variants: PlasmicRecommendedVillas__VariantsArgs;
  args: PlasmicRecommendedVillas__ArgsType;
  overrides: PlasmicRecommendedVillas__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_visitors_css.plasmic_tokens,
        sty.root
      )}
    >
      <RecommendedVillas2
        data-plasmic-name={"recommendedVillas2"}
        data-plasmic-override={overrides.recommendedVillas2}
        className={classNames("__wab_instance", sty.recommendedVillas2)}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "recommendedVillas2"],
  recommendedVillas2: ["recommendedVillas2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  recommendedVillas2: typeof RecommendedVillas2;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicRecommendedVillas__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicRecommendedVillas__VariantsArgs;
    args?: PlasmicRecommendedVillas__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicRecommendedVillas__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicRecommendedVillas__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicRecommendedVillas__ArgProps,
          internalVariantPropNames: PlasmicRecommendedVillas__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicRecommendedVillas__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRecommendedVillas";
  } else {
    func.displayName = `PlasmicRecommendedVillas.${nodeName}`;
  }
  return func;
}

export const PlasmicRecommendedVillas = Object.assign(
  // Top-level PlasmicRecommendedVillas renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    recommendedVillas2: makeNodeComponent("recommendedVillas2"),

    // Metadata about props expected for PlasmicRecommendedVillas
    internalVariantProps: PlasmicRecommendedVillas__VariantProps,
    internalArgProps: PlasmicRecommendedVillas__ArgProps
  }
);

export default PlasmicRecommendedVillas;
/* prettier-ignore-end */
